### ISSUE TITLE
Failed to resolve firebase-ui-database and firebase-ui-auth

### ISSUE THREAD

**Issue by MrBrightside29** [firebase/FirebaseUI-Android#125]
I've tried to update my firebase-ui dependency from 0.3.1 to 0.4.0 but Gradle Sync fails to resolve dependencies.
```
Error:Failed to resolve: com.firebaseui:database:0.4.0
Error:Failed to resolve: com.firebaseui:auth:0.4.0
```
Thanks in advance.

**Comment by samtstern** [comment]
@MrBrightside29 do you have 'jcenter()' in your repositories in your build.gradle file?

**Comment by MrBrightside29** [comment]
@samtstern Yes, just below mavenCentral. With 0.3.1 works just fine. Maybe, it could be due to 0.4.0 is not available in mavenCentral?

**Comment by tjerkw** [comment]
Some problem:

I copy pasted
`
    
    // Single target that includes all FirebaseUI libraries
    compile 'com.firebaseui:firebase-ui:0.4.0'

    // FirebaseUI Database only
    compile 'com.firebaseui:firebase-ui-database:0.4.0'

    // FirebaseUI Auth only
    compile 'com.firebaseui:firebase-ui-auth:0.4.0'`

(BTW you are using # instead of // in the documentation here: https://github.com/firebase/FirebaseUI-Android

Then after gradle sync i get: 

> Error:Could not find com.firebaseui:database:0.4.0.
Required by:
    tiqetsapp-android:app:unspecified
    tiqetsapp-android:app:unspecified > com.firebaseui:firebase-ui:0.4.0
<a href="searchInBuildFiles">Search in build.gradle files</a>


I do have jcenter() as a repo.

**Comment by tjerkw** [comment]
Even adding the dependency 

> 
    compile 'com.firebaseui:database:0.4.0'

Doesnt help

**Comment by tjerkw** [comment]
I looked into the sample app, this should be the imports:

> 
    // For firebase sign in
    compile "com.google.firebase:firebase-database:9.0.0"
    compile "com.google.firebase:firebase-auth:9.0.0"

**Comment by MrBrightside29** [comment]
@samtstern I've added the dependencies of ui-database and ui-auth separated instead of single dependency and it works fine.
I've also noticed that using the single dependency, gradle maybe fails to resolve because is looking for 'com.firebaseui:database:0.4.0' instead of 'com.firebaseui:firebase-ui-database:0.4.0'. Same for auth.

@tjerkw I think you are a little bit confused about the dependecies. Is not the same 
```
"com.google.firebase:firebase-database:9.0.0"
"com.google.firebase:firebase-auth:9.0.0"
```
and
```
"com.firebaseui:firebase-ui-database:0.4.0"
"com.firebaseui:firebase-ui-auth:0.4.0"
```
Actually, firebaseUI depends on the first ones to work.

**Comment by sdeff** [comment]
0.4.0. [is not available on Maven](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.firebaseui%22%20AND%20a%3A%22firebase-ui%22).

**Comment by tremerhl** [comment]
Instead of adding `compile 'com.firebaseui:firebase-ui:0.4.0' `
**add** 
`compile 'com.firebaseui:firebase-ui-database:0.4.0'` 
**or**
 `compile 'com.firebaseui:firebase-ui-auth:0.4.0'`
**or add both**

**Comment by samtstern** [comment]
@sdeff that's working as intended, FirebaseUI 0.3.x was published to MavenCentral but we moved to jcenter now since that's the default repository for all Android libraries.

**Comment by samtstern** [comment]
@MrBrightside29 are you still have this issue?  Do you only see it with `'com.firebaseui:firebase-ui:0.4.0'` or are you also unable to resolve `'com.firebaseui:firebase-ui-database:0.4.0' `.

**Comment by MrBrightside29** [comment]
@samtstern I'm able to resolve it using separated dependencies
```
compile 'com.firebaseui:firebase-ui-database:0.4.0'
compile 'com.firebaseui:firebase-ui-auth:0.4.0'
```
Thanks

**Comment by samtstern** [comment]
Ok I'm glad that solved your problem.  For what it's worth, `com.firebaseui:firebase-ui:0.4.0` is just an empty library that declares dependencies on those libraries for convenience.

I will leave this issue open until I can figure out what's going on with my jCenter configuration, thanks for the report!

**Comment by samtstern** [comment]
Should be fixed now, closing.  Re-open if you do a clean build and still see issues.

**Comment by adamkoch** [comment]
This is still happening for me, same error when just using firebase-ui:0.4.0 -
Error:Failed to resolve: com.firebaseui:database:0.4.0
Error:Failed to resolve: com.firebaseui:auth:0.4.0

Switching to the two components works fine:
    compile 'com.firebaseui:firebase-ui-database:0.4.0'
    compile 'com.firebaseui:firebase-ui-auth:0.4.0'

Is firebase-ui referencing the wrong libs? (com.firebaseui:database instead of com.firebaseui:firebase-ui-database)

**Comment by samtstern** [comment]
@adamkoch your comment is the first one where I think I actually understand the issue here.

Yes it's very likely I botched the POM generation for firebaseui (the monolith).  Re-opening to investigate.

**Comment by samtstern** [comment]
Confirmed this is an issue (and my fault).  Please use the individual dependencies for now.

**Comment by samtstern** [comment]
Ok I just pushed a fix for this.  There will be some propagation delay.  @adamkoch if you can try it in >= 1hr and let me know if it works that would be great.  Just build your project with the gradle flag `--refresh-dependencies` to make sure it re-downloads deps and does not use the cached copy.

**Comment by adamkoch** [comment]
Just checked and it has already propagated and is working fine now. Thanks! :)

**Comment by Danm72** [comment]
Great work, been waiting for this fix

**Comment by abhilash1in** [comment]
I'm still facing the same issue. 

`compile 'com.firebaseui:firebase-ui:0.4.0'` gives me
```
Error:Failed to resolve: com.firebaseui:database:0.4.0
Error:Failed to resolve: com.firebaseui:auth:0.4.0
```

**Comment by Danm72** [comment]
Did you try building with the refresh dependencies argument

**Comment by abhilash1in** [comment]
I added the dependency only today, so it should fetch the latest one I guess? I'd used it once before in another project though. Will android studio try to re-use that? If so, that would just repeat this problem. How do I refresh dependencies?

**Comment by Danm72** [comment]
./gradlew build --refresh-dependencies, I'm not sure why it didn't fetch it after you added it today.

I also found downloading the source and running the maven publish local task to work for now

**Comment by samtstern** [comment]
@abhilash1in also make sure that your project has `jcenter()` in the repositories block.

**Comment by zahid--ali** [comment]
I am facing the same issue. Can someone help me out in this situation

**Comment by samtstern** [comment]
Closing this issue, it's very old and FirebaseUI has been available on jcenter for a while now.

**Comment by huxaiphaer** [comment]
Oooh gosh me too am facing the same problem

**Comment by RicardoAlgarin** [comment]
Hello,
I have the same problem, I have not been able to resolve, with:

Error:(35, 13) Failed to resolve: compile 'com.firebaseui:firebase-ui-database:0.4.0'. please help me.

**Comment by SUPERCILEX** [comment]
Please use the latest version of the library: 1.0.0.

**Comment by RicardoAlgarin** [comment]
Thank you @SUPERCILEX .

**Comment by SUPERCILEX** [comment]
You're welcome!

**Comment by pshoultz** [comment]
same problem and the fixes on here don't seem to work.  Is there an answer in 2018?

**Comment by kaivan-s** [comment]
`dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    compile 'com.google.firebase:firebase-core:11.8.0'
    compile 'com.google.firebase:firebase-database:11.8.0'
    compile 'com.firebaseui:firebase-ui:0.4.0'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
}
apply plugin: 'com.google.gms.google-services'`

> Some error with appcompat and firebase-core

**Comment by AnthonyBeaulaMary** [comment]
Change the build.gradle(project) file as follows:

allprojects {
    repositories {
        google()
        jcenter()
        **maven { url 'https://maven.fabric.io/public' }**
    }
}

Hope you will find a solution.
