### ISSUE TITLE
Add ability to specify default_web_client_id at runtime

### ISSUE THREAD

**Issue by edenman** [firebase/FirebaseUI-Android#1911]
### Step 1: Are you in the right place?

  * Yes 

### Step 2: Describe your environment

  * com.google.firebase:firebase-messaging:20.2.3
  * com.firebaseui:firebase-ui-auth:7.1.1
  
### Step 3: Describe the problem:

I'm trying to push a build of my app that is capable of switching between Prod and Staging at runtime.  My production API server uses one Firebase project, my staging API server uses a staging Firebase project.  Following [these instructions](https://firebase.google.com/docs/projects/multiprojects#support_multiple_environments_in_your_android_application), I have managed to get the `FirebaseApp.initializeApp` part of this working, but AuthUI's `GoogleProvider` requires that `default_web_client_id` be set in strings.xml.  This breaks me because I need to change that value at runtime.  It would be great if this value could be provided at runtime.
  
#### Relevant Code:

  ```
    val providers = arrayListOf(
      AuthUI.IdpConfig.AppleBuilder().build(),
      AuthUI.IdpConfig.GoogleBuilder().build(),
      AuthUI.IdpConfig.EmailBuilder().build()
    )
  ```
ideally something like:
```
    val providers = arrayListOf(
      AuthUI.IdpConfig.AppleBuilder().build(),
      AuthUI.IdpConfig.GoogleBuilder().defaultWebClientID("foo").build(),
      AuthUI.IdpConfig.EmailBuilder().build()
    )
```

#### Workaround:

If anybody else hits this: you can remove the Google sign-in option when pointing at your Staging environment.

**Comment by samtstern** [comment]
@edenman thank you for this, I think this is a reasonable feature request.

**Comment by samtstern** [comment]
This was fixed and released in version `7.2.0`

**Comment by edenman** [comment]
@samtstern thanks! I don't see any method on `GoogleSignInOptions.Builder` to set this value in `play-services-base:17.1.0`.  Was the associated change not released in that library yet?

**Comment by edenman** [comment]
com.google.firebase:firebase-auth:21.0.1
depends on 
com.google.android.gms:play-services-auth-api-phone:17.4.0
depends on 
com.google.android.gms:play-services-base:17.1.0

...looks like there's a 17.6.0 of play-services-base but even if I force update that library, I still don't see a setter for it?  Although the code obfuscation is making it hard to tell.  What's the method supposed to be called?

**Comment by edenman** [comment]
oh wow is it `requestIdToken()`?

**Comment by samtstern** [comment]
@edenman yep it's `requestIdToken()`, that's the only place that Client ID was ever used. The "web client ID" is needed in order to make sure the audience on the ID token is correct so that Firebase Auth can validate it when you call `signInWithCredential`
