### ISSUE TITLE
[Known Issue] Error: Failed to resolve: com.twitter.sdk.android:twitter:2.0.0 when syncing with Gradle

### ISSUE THREAD

**Issue by amandle** [firebase/FirebaseUI-Android#392]
If you are upgrading a project to version 1.0.0 you may encounter the error `Failed to resolve: com.twitter.sdk.android:twitter:2.0.0` when syncing your project with Gradle. Version 1.0.0 has added a new required configuration step. To resolve this issue you must add the Fabric repository to your repositories:

```groovy
repositories {
    // ...
    maven { url 'https://maven.fabric.io/public' }
}
```

**Comment by kirtan403** [comment]
Adding this to readme will be better.

**Comment by samtstern** [comment]
@kirtan403 we have it in the [auth README](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/README.md).  You don't need this repository addition if you're only using database or storage.

**Comment by kirtan403** [comment]
@samtstern  Ohh.. I didn't checked the auth one. I checked the main one. Thanks for pointing that out. 😄 Is it really needed even if I do not use twitter authentication?

**Comment by samtstern** [comment]
@kirtan403 it's needed just to get gradle to be happy since the Twitter Android SDK is listed as a transitive dependency in the `pom.xml`.  If you use ProGuard on your application this should not have a large size impact.

We are looking for ways in later versions to remove this friction.

**Comment by jay-thakur** [comment]
I have added fabric repository to build.gradle(App) as - 

```
repositories {
    mavenLocal()
    flatDir {
        dirs 'libs'
    }
    maven { url 'https://maven.fabric.io/public' }
}
```

Getting Error - 

> Error:Could not download gson.jar (com.google.code.gson:gson:2.6.1): No cached version available for offline mode

I added gson dependency but didn't work.
@amandle  @samtstern **Please Suggest.**

@kirtan403 did your issue resolved by adding fabric repo only ?

**Comment by SUPERCILEX** [comment]
@jay-thakur see this stack overflow post on how to turn off offline mode: http://stackoverflow.com/q/28712025/4548500

And of course make sure you are online.

**Comment by jay-thakur** [comment]
@SUPERCILEX thanks. Worked.

**Comment by itpablo** [comment]
Even adding the reference the problem remains guys (same as reported in the issue title). I can compile only in the 0.6.2 version.

My gradle:

`
(...)
    repositories {
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }
(...)
`

I'm syncing with the online configuration.

Thanks!

**Comment by GaborPeto** [comment]
I had the same problem in 1.0.0 and solved it.
I have an android app module with an android library module (authentication).
The authentication module has dependency on firebaseUI. I received the error above and solved it by adding the repositories to both build.gradle files. Not sure why this works, but I hope it helps:

app/build.gradle:

```
android {

  repositories {
    maven { url 'https://maven.fabric.io/public' }
  }
...
```

authentication/build.gradle:

```
android {

  repositories {
    maven { url 'https://maven.fabric.io/public' }
  }
...
```

**Comment by itpablo** [comment]
Yeah @GaborPeto,  i have two modules and the problem is solved now when i just put the repository in the app\build.gradle

Before i was trying to put the declaration on build.gradle general file common to all sub-projects/modules

There is no need for me to repeat the repository in the two build.gradle files for both of modules.

Anyway thanks very mutch GaborPeto for the advice!

**Comment by GaborPeto** [comment]
I'm pretty sure I tested that the I got tge error if I didn't put the repositories into both build.grdale files. But if you're saying it is working I might just double check it as I really dont like the fact that I have to duplicate that piece of config.

**Comment by GaborPeto** [comment]
So just an update on my previous comment:
Removing the config 
```
repositories {
    maven { url 'https://maven.fabric.io/public' }
  }
```
from either of app/build.gradle or authentication/build.gradle results in `Failed to resolve: com.twitter.sdk.android:twitter:2.0.0` exception.

**Comment by isurum** [comment]
@GaborPeto Add repository to allprojects as well.

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.2'
        classpath 'com.google.gms:google-services:3.0.0'
        
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by GaborPeto** [comment]
Thank @isurum, that works too

**Comment by yawarali** [comment]
![9](https://cloud.githubusercontent.com/assets/17020418/20822314/8024e8b6-b86b-11e6-811a-2ce46f68bab7.PNG)

**Comment by kirtan403** [comment]
@yawarli Check the first post.

Add this line: 
`maven { url 'https://maven.fabric.io/public' }`  
inside `repositories` in the screenshot you posted.

**Comment by yawarali** [comment]
Same Issue :)
![10](https://cloud.githubusercontent.com/assets/17020418/20822581/938523b0-b86d-11e6-8547-688161e60513.PNG)

**Comment by SUPERCILEX** [comment]
@yawarali, put it in your `allprojects` repositories. 😄

**Comment by kirtan403** [comment]
@yawarali  You already have repositories section (just above the error). Just add that single line after jcenter().

**Comment by yawarali** [comment]
@kirtan403 I did as you said. Please see second screenshot.
@SUPERCILEX  what is "allprojects"? Where is it?

**Comment by SUPERCILEX** [comment]
@yawarali:
![image](https://cloud.githubusercontent.com/assets/9490724/20822680/a290bb56-b801-11e6-80f0-b46dd3123a3e.png)

**Comment by kirtan403** [comment]
@SUPERCILEX I was just creating it in paint! Thanks 😄

**Comment by SUPERCILEX** [comment]
@kirtan403 I have a secret trick for being so fast: the "Snipping Tool". It's the best thing ever! You can quickly select an area to take a screenshot of and then Ctrl+C and Ctrl+V it directly into a post. It's way faster than PrtScr->paste into paint->crop->select all->copy 'n paste. Anyway, just me being nerdy. 😄

**Comment by kirtan403** [comment]
@SUPERCILEX haha! I didn't knew it can be pasted directly here! I though I can just drag the jpg/png here! Now windows ink tool with screen sketch is also good! Thanks for the tip 😃

**Comment by yawarali** [comment]
Hahaha guys new error
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [com.firebaseui:firebase-ui-auth:1.0.1] C:\Users\Qaisar Aslam Mayo\AndroidStudioProjects\FirebaseDemo\app\build\intermediates\exploded-aar\com.firebaseui\firebase-ui-auth\1.0.1\AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="com.firebase.ui.auth" to force usage
![11](https://cloud.githubusercontent.com/assets/17020418/20822868/35f2bd5e-b870-11e6-9f92-b80c57e5eb6d.PNG)

**Comment by SUPERCILEX** [comment]
FirebaseUI only support minSdk 16 so you have to go to your app `build.gradle` and set `minSdkVersion 16`.

**Comment by yawarali** [comment]
@kirtan403 @SUPERCILEX  Thanks guys all issue are resolved. This is my first experience, real time communication.

**Comment by kirtan403** [comment]
@yawarali Your welcome 👍  Enjoy firebase 😄

**Comment by SUPERCILEX** [comment]
Glad to hear that! Have fun! 😄

**Comment by Alfonsibo** [comment]
In my case com.twitter.sdk.android:twitter:2.0.0 was solved adding the code below into app/gradle and upgrading minSdkVersion to 16:  `
android {
    repositories {
            maven { url 'https://maven.fabric.io/public' }
    }
}` 

Thanks! :) @GaborPeto @SUPERCILEX 

P.S. Sorry for the format, I have never posted an issue before :(

**Comment by bpappin** [comment]
just an update in case this is still confusing some:
Adding the dependency to the allprojects section did not work, I had to add it to the android section in the same module that had the firebase-auth-ui dependency.

**Comment by SUPERCILEX** [comment]
@samtstern Since `1.1.0` has been released, do you think this issue can be closed now? It was mostly intended as an upgrade guide for `1.0.0` which is now outdated.

**Comment by samtstern** [comment]
I think given that it's in the Auth README we can close this issue.  It's not "fixed" but the workaround is documented.

**Comment by ay1man4** [comment]
V1.0.0 is working without issues but dependencies not resolved for all versions after it.

**Comment by ay1man4** [comment]
I found the solution:
1- in project build.gradle add fabric repository in one place as below:
```
allprojects {
    repositories {
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }
}
```
2- in project manifest file make sure to change rtl support to false as it conflict with firebase-ui:
```
    <application
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        **android:supportsRtl="false"**
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

```

**Comment by BrownEli** [comment]
I followed the guide in the README for version 1.2.0 adding the needed dependency and fabric repository 
and ran into thease errors here after Gradle sync..

Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

Is there a documented workaround for errors in this area?

**Comment by samtstern** [comment]
@BrownEli that sounds like something different, please file a new issue

**Comment by dmbfaisal** [comment]
@BrownEli  I am getting the same error, how did you solve it?

**Comment by BrownEli** [comment]
I just used a newer version on the library.

**Comment by dmbfaisal** [comment]
@BrownEli Thanks and here by 'library' you mean firebase auth ui. Right???

**Comment by nabeelnazir163** [comment]
![help](https://user-images.githubusercontent.com/30865060/29917075-33d39ff0-8e5a-11e7-97fb-142e878239e5.png)

I am having this issue now !! How to fix this problem

**Comment by BrownEli** [comment]
My guess is because, firebaseui is also also adding the facebook app id,
you need to replace what the library is doing.
This should work! Let me know if it helped.

<meta-data android:name="com.facebook.sdk.ApplicationId"
            tools:replace="android:value"
            android:value="your facebook app id"/>
